### ISSUE TITLE
Feature Request - Unsubscribe Support

### ISSUE THREAD

**Issue by mbabker** [BitBagCommerce/SyliusMailChimpPlugin#1]
Knowing full well this would be a little more involved, it would be cool if unsubscribe support were available as well to handle conditions where a user updates their profile and `$customer->isSubscribedToNewsletter()` goes from true to false.

**Comment by bitbager** [comment]
Thank you once again. Especially for you this was also improved in 787e62e7e8c935d3152486db6de915086ad4b522 commit 🎉

**Comment by mbabker** [comment]
Thanks!
