### ISSUE TITLE
French translations

### ISSUE THREAD

**Issue by Vowow** [BitBagCommerce/SyliusMailChimpPlugin#11]
Hello,

There's still no french translations that I added in the last release.
Can you check @bitbager  ?

Thank you

**Comment by bitbager** [comment]
Could you customize your PR to use `bitbag_sylius_mailchimp_plugin.ui.` translation ID prefix?

**Comment by Vowow** [comment]
@bitbager done (https://github.com/BitBagCommerce/SyliusMailChimpPlugin/pull/12) sorry for the delay
