### ISSUE TITLE
MailChimp Mailmotor bundle

### ISSUE THREAD

**Issue by jeroendesloovere** [BitBagCommerce/SyliusMailChimpPlugin#13]
Hi there,

I have created a library called "mailmotor" which has a "standarized" subscribe/unsubscribing process using any mail engine (currently works with MailChimp and CampaignMonitor).

Maby you guys can create a SyliusNewsletterPlugin which can connect to any mail engines (and not only MailChimp)... 

Please check the [mailmotor-bundle](https://github.com/mailmotor/mailmotor-bundle) out.

**Comment by KrisFlorq** [comment]
Thank You for your suggestion, this bundle is going to support only mailchimp for now.
