### ISSUE TITLE
Blank page when subscribing to the newsletter

### ISSUE THREAD

**Issue by ghost** [BitBagCommerce/SyliusMailChimpPlugin#15]
Hello,

When subscribing to the newsletter, I have the following result:

![image](https://user-images.githubusercontent.com/38758765/42933567-5db3fb60-8b45-11e8-9867-de48d70bee2d.png)

That's all I have in the page. The email address I'm trying to subscribe isn't even subscribed to the newsletter.
I haven't tried to submit the form using Ajax.

**Comment by bitbager** [comment]
Seems like you have not used our jQuery plugin. Read the README and you should be fine 🙂
