### ISSUE TITLE
404 Resource not found

### ISSUE THREAD

**Issue by ghost** [BitBagCommerce/SyliusMailChimpPlugin#16]
Hi,

If you got this error when entering a new email address  :

> 404
> ResourceNotFound
> The requested resource could not be found.
> 
> This error tells you a specific resource doesn’t exist. It’s possible that the resource has been moved or deleted, or that there’s a typo in your request.

Don't forget to add quotes to your API KEY and LIST ID.
It'll escape you to loose one full morning.

PS: you should edit the readme for the new version of Sylius (1.3) with Symfony 4 (it's change lot of things about the installation)

**Comment by tbuczen** [comment]
Thanks for submitting this issue, fix with better error messages is currently in progress.
