### ISSUE TITLE
subsrice from checkout form

### ISSUE THREAD

**Issue by seriousTom** [BitBagCommerce/SyliusMailChimpPlugin#37]
Is it possible using this plugin send email address to the mailchimp which user specifies in checkout proccess?

**Comment by tbuczen** [comment]
To begin with, I suggest checking compliance with the GDPR, usually you have to ask the user for consent to be added to the mailing list.

Its possible to call public method subscribe from NewsletterSubscriptionHandler service which is defined as a service `bitbag_sylius_mailchimp_plugin.handler.newsletter_subscription_handler`

Whole list of services and forms that you can decorate and extend lays here: https://github.com/BitBagCommerce/SyliusMailChimpPlugin#customization

There is no plug and play possibility of automatically adding user to the mailchimp list at some state of order process.

**Comment by KrisFlorq** [comment]
Because of the lack of response we are closing this issue.
