### ISSUE TITLE
Option to disable the plugin conditionally

### ISSUE THREAD

**Issue by arjanfrans** [BitBagCommerce/SyliusMailChimpPlugin#45]
I have the use case that I do not want to have the plugin enabled all the time. For example, in a development environment or a review environment. (A "review environment" also runs as `APP_ENV=prod`, so using the different environment directories for configs is not an option)

I currently have a compiler pass that checks if the `mailchimp.api_key` is empty/null. If that is the case, I replace the newsletter subscription handler with a dummy and disable all other unnecessary services.

```
<?php

namespace App\Mailchimp;

use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;

/**
 * Compiler pass to disable some mailchimp services if the API Key is not configured.
 * This is useful to disable mailchimp for development or review environments.
 */
class DisableMailchimpCompilerPass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container): void
    {
        $mailchimpApiKey = $container->resolveEnvPlaceholders(
            $container->getParameter('mailchimp.api_key'),
            true
        );

        if (null !== $mailchimpApiKey && !empty($mailchimpApiKey)) {
            return;
        }

        $newsletterSubscriber = $container->getDefinition('bitbag_sylius_mailchimp_plugin.handler.newsletter_subscription_handler');
        $newsletterSubscriber->setClass(NullNewsletterSubscriptionHandler::class);
        $newsletterSubscriber->setArguments([]);

        $container->removeDefinition('bitbag_sylius_mailchimp_plugin.event_listener.customer_listener');
        $container->removeDefinition('bitbag_sylius_mailchimp_plugin.drewm.mailchimp');
        $container->removeDefinition('bitbag_sylius_mailchimp_plugin.validator.webhook_validator');
        $container->removeDefinition('bitbag_sylius_mailchimp_plugin.controller.mailchimp');
    }
}
```

I like the solution that we have right now, but wouldn't it be nice to provide this out-of-the-box?

**Comment by senghe** [comment]
Hi @arjanfrans

We do not plan the functionality you mentioned about. But you can achieve this by making your own environment variable, and then using it in a condition inside i.e. in bundles.php file (or something similar). Then it doesn't touch the plugin's code.
