### ISSUE TITLE
Try solving You have requested a non-existent parameter "mailchimp.webhook_secret" 

### ISSUE THREAD

**Issue by kiakahaDZ** [BitBagCommerce/SyliusMailChimpPlugin#47]
hello i use sylius ecommerce platforme after doing composer update i get the follow error is there a solution please 
**"You have requested a non-existent parameter "mailchimp.webhook_secret"."**

**Comment by kuba-end** [comment]
In config/packages/_sylius.yaml add 
```
parameters:
    mailchimp.webhook_secret: '%env(resolve:MAIL_CHIMP_WEBHOOK_SECRET)%'

**Comment by senghe** [comment]
Hi @kiakahaDZ, I've updated the installation docs to add the parameter(s) mentioned by @kuba-end to `_sylius.yaml` file. I'm closing the issue.
